name: Bootcamp Task Template
description: This template is used to create issues for Bootcamp tasks
title: "[Bootcamp] My first bootcamp task"
labels: bootcamp
body:
  - type: textarea
    attributes:
      label: Task Brief
      description: Describe the task. You may add screenshots to create context.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Deliverables
      description: Describe what should be changed and how it should behave.
    validations:
      required: true
  - type: input
    attributes:
      label: Estimated Completion Time
      placeholder: 2 hours
    validations:
      required: true
  - type: markdown
    attributes:
      value: "*If you start to exceed the number of hours, it's okay. Reach out to your mentor for help and they can guide you through the task.*"
  - type: textarea
    attributes:
      label: Reviewers
      description: Add DRIs to review the changes. Most likely the tech leads of the project
      placeholder: '@scottylabs'
    validations:
      required: true
  - type: markdown
    attributes:
      value: "*Add the people above to as reviewers of your Pull Request when you submit your changes*"